### ISSUE TITLE
Error trying this on RunKit: Cannot find module 'doctype-to-string'

### ISSUE THREAD

**Issue by simonw** [WebMemex/freeze-dry#53] opened 2020-04-23 17:27 UTC
I tried using https://runkit.com/ to experiment with this library, but I got the following error:

<img width="1127" alt="Screenshot_4_23_20__10_27_AM" src="https://user-images.githubusercontent.com/9599/80130195-13d62a00-854d-11ea-8948-e52fff0147ee.png">

**Comment by simonw** [comment] 2020-04-23 17:53
Maybe this is because freeze-dry is a purely client-side library, not designed to run in server-side Node.js?

**Comment by Treora** [comment] 2020-04-23 22:08
Thanks for reporting.

> Maybe this is because freeze-dry is a purely client-side library, not designed to run in server-side Node.js?

That should not be the problem; it runs fine in Node (using e.g. jsdom); that’s what the freeze-dry tests do too.

The problem is most likely that Runkit only resolves package dependencies that are coming from the official npm registry. In fact it sounds like they just keep a copy of it:

> all of npm's 400,000 packages are already pre-installed, just require() them

But then that fails when a package depends on packages from elsewhere, like `document-outerhtml` that has these lines in its `package.json`:

    "dependencies": {
      "doctype-to-string": "git+https://code.treora.com/gerben/doctype-to-string#semver:^0.1.3"
    },

So I suppose this would be an issue to report to Runkit.

For your interest, the `doctype-to-string` and `document-outerhtml` modules are the first ones I started self-publishing outside of the npm registry (not coincidentally the day it got bought by GitHub). It is partly an experiment see how much the javascript/node/npm ecosystem has been tied to this single registry. My apologies for you having discovered the first incompatibility!

**Comment by Treora** [comment] 2020-04-23 22:18
From a quick search on Runkit’s forum, [this](https://discuss.runkit.com/t/dependent-library-not-found/633/3) from December 2017 seems to confirm the suspicion:

>  …. RunKit doesn’t currently support git dependencies (although it is something we’d like to eventually support). You will have to publish that package to NPM in order to use it in RunKit.

I will close this issue here, though I’d be glad to hear if there is any follow-up or similar problems elsewhere.

**Closed by Treora** 2020-04-23 22:18 UTC
